[project]
name = "wmoutils"
version = "0.0.0"  # DO NOT SET. The version of the package is always set by the CI/CD pipeline.
description = "Collection of Python utility functions to interact with WMO APIs, incl. OSCAR and WDQMS."
license = "BSD-3-Clause"
authors = [
    {name = "F.P.A Vogt", email = "frederic.vogt@meteoswiss.ch"},
    {name = "E. Sauvageat"}
]
maintainers = [
    {name = "F.P.A Vogt", email = "frederic.vogt@meteoswiss.ch"}
]
readme = "README.rst"
include = ["CHANGELOG.rst"]
packages = [{include = "*", from="src"}]
requires-python = ">=3.11"
dependencies = [
    "polars",
    "requests",
]
keywords = ["WMO", "GBON", "meteorology", "climate", "data", "utilities", "OSCAR"]
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable

    'Development Status :: 3 - Alpha',

    # Indicate who your project is intended for
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Atmospheric Science',

    # Pick your license as you wish (should match "license" above)
    'License :: OSI Approved :: BSD License',

    # Specify the Python versions you support here. In particular, ensure
    # that you indicate whether you support Python 2, Python 3 or both.
    'Programming Language :: Python :: 3',
]

[projects.urls]
Homepage = "https://meteoswiss.github.io/wmoutils"
Documentation = "https://meteoswiss.github.io/wmoutils"
Repository = "https://github.com/MeteoSwiss/wmoutils/"
Issues = "https://github.com/MeteoSwiss/wmoutils/issues"
Changelog = "https://github.com/MeteoSwiss/wmoutils/blob/main/CHANGELOG.rst"

[dependency-groups]
dev = [
    "mypy (>=1.18.1)",
    "pydata-sphinx-theme (>=0.16.1)",
    "pylint (>=3.3.8)",
    "pytest (>=8.4.2)",
    "pytest-cov (>=7.0.0)",
    "sphinx (>=8.2.3)",
    "sphinx-autoapi (>=3.6.0)",
    "yapf (>=0.43.0)",
]

[tool.poetry]
include = []

[tool.yapf]
based_on_style = "pep8"
column_limit = "120"

[tool.pylint.master]
disable = [
    'C0114', # missing-module-docstring
    'C0115', # missing-class-docstring
    'C0116', # missing-function-docstring
    'W0511', # fix me or to-do comments are already covered by SonarQube
]

[tool.pylint.basic]
argument-naming-style = 'any'
attr-naming-style = 'any'

[tool.pylint.format]
# Maximum number of lines in a module.
max-line-length = 120

[tool.pylint.design]
# Minimum number of public methods for a class (see R0903).
min-public-methods = 0

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.coverage.run]
omit = ["test/**",  "doc/**"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
